import { NextApiRequest, NextApiResponse } from 'next';

export default function (req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'GET') {
    return res.status(200).json([
      {
        title: 'africa',
        countries: '54',
        languages: '~2000',
        description:
          'A África é um continente localizado na zona intertropical, com maior parte do seu território no Hemisfério Sul. Possui mais de um bilhão de habitantes e 30 milhões de km2 de extensão, sendo, por isso, considerado um dos maiores e mais populosos continentes do mundo.',
        image: '/continents/africa.jpg',
        mostVisitedCities: [
          { rank: '54', city: 'Johannesburg', country: 'South Africa' },
          { rank: '75', city: 'Marrakech', country: 'Morocco' },
        ],
      },
      {
        title: 'asia',
        countries: '48',
        languages: '2300',
        description:
          'A Ásia é o maior continente em área terrestre do mundo, estando boa parte do continente localizado no Hemisfério Norte. Além de ser o mais extenso, é também o mais populoso, habitando nele cerca de três quintos da população mundial. A Ásia é multicultural, abrigando diversas culturas, etnias, religiões e tradições.',
        image: '/continents/asia.jpg',
        mostVisitedCities: [
          { rank: '1', city: 'Hong Kong', country: 'China (SAR)' },
          { rank: '2', city: 'Bangkok', country: 'Thailand' },
          { rank: '4', city: 'Macau', country: 'China (SAR)' },
          { rank: '5', city: 'Singapore', country: 'Singapore' },
          { rank: '7', city: 'Dubai', country: 'Emirados Árabes Unidos' },
          { rank: '9', city: 'Kuala Lumpur', country: 'Malaysia' },
          { rank: '10', city: 'Istanbul', country: 'Turkey' },
          { rank: '11', city: 'Delhi', country: 'India' },
          { rank: '12', city: 'Antalya', country: 'Turkey' },
          { rank: '13', city: 'Shenzhen', country: 'China' },
          { rank: '14', city: 'Mumbai', country: 'India' },
          { rank: '15', city: 'Phuket', country: 'Thailand' },
          { rank: '17', city: 'Tokyo', country: 'Japan' },
          { rank: '18', city: 'Pattaya', country: 'Thailand' },
          { rank: '19', city: 'Taipei Taiwan', country: ' China' },
          { rank: '20', city: 'Mecca', country: 'Saudi Arabia' },
          { rank: '21', city: 'Guangzhou', country: 'China' },
          { rank: '23', city: 'Medina', country: 'Saudi Arabia' },
          { rank: '24', city: 'Seoul', country: 'South Korea' },
          { rank: '26', city: 'Agra', country: 'India' },
          { rank: '28', city: 'Osaka', country: 'Japan' },
          { rank: '30', city: 'Shanghai', country: 'China' },
          { rank: '31', city: 'Ho Chi Minh City', country: 'Vietnam' },
          { rank: '32', city: 'Denpasar', country: 'Indonesia' },
          { rank: '36', city: 'Chennai', country: 'India' },
          { rank: '38', city: 'Johor Bahru', country: 'Malaysia' },
          { rank: '39', city: 'Jaipur', country: 'India' },
          { rank: '42', city: 'Cairo', country: 'Egypt' },
          { rank: '45', city: 'Moscow', country: 'Russia' },
          { rank: '48', city: 'Ha Long', country: 'Vietnam' },
          { rank: '49', city: 'Riyadh', country: 'Saudi Arabia' },
          { rank: '52', city: 'Ha Noi', country: 'Vietnam' },
          { rank: '57', city: 'Jakarta', country: 'Indonesia' },
          { rank: '58', city: 'Beijing', country: 'China' },
          { rank: '59', city: 'St. Petersburg', country: 'Russia' },
          { rank: '61', city: 'Jerusalem', country: 'Israel' },
          { rank: '64', city: 'Dammam', country: 'Saudi Arabia' },
          { rank: '65', city: 'Penang Island', country: 'Malaysia' },
          { rank: '67', city: 'Kyoto', country: 'Japan' },
          { rank: '68', city: 'Zhuhai', country: 'China' },
          { rank: '70', city: 'Chiang Mai', country: 'Thailand' },
          { rank: '76', city: 'Kolkatta', country: 'India' },
          { rank: '77', city: 'Cebu', country: 'Philippines' },
          { rank: '79', city: 'Tel Aviv', country: 'Israel' },
          { rank: '80', city: 'Guilin', country: 'China' },
          { rank: '82', city: 'Hurgada', country: 'Egypt' },
          { rank: '86', city: 'Chiba', country: 'Japan' },
          { rank: '90', city: 'Da Nang', country: 'Vietnam' },
          { rank: '91', city: 'Batam', country: 'Indonesia' },
          { rank: '93', city: 'Fukuoka', country: 'Japan' },
          { rank: '94', city: 'Abu Dhabi', country: 'Emirados Árabes Unidos' },
          { rank: '95', city: 'Jeju', country: 'South Korea' },
          { rank: '99', city: 'Krabi', country: 'Thailand' },
          { rank: '100', city: 'Bangalore', country: 'India' },
        ],
      },
      {
        title: 'europe',
        countries: '44',
        languages: '24',
        description:
          'Europa é um dos seis continentes do mundo, sendo em extensão territorial o segundo menor. O continente é banhado, ao norte, pelo Mar Ártico; ao sul, pelo Mar Mediterrâneo e o Mar Negro; a oeste, pelo Oceano Atlântico; e, a leste, pelo Mar Cáspio. A Europa é também conhecida como o “Velho Mundo” e considerada o berço da cultura ocidental.',
        image: '/continents/europe.jpg',
        mostVisitedCities: [
          { rank: '3', city: 'London', country: 'United Kingdom' },
          { rank: '6', city: 'Paris', country: 'France' },
          { rank: '16', city: 'Rome', country: 'Italy' },
          { rank: '22', city: 'Prague', country: 'Czechia' },
          { rank: '25', city: 'Amsterdam', country: 'Netherlands' },
          { rank: '33', city: 'Barcelona', country: 'Spain' },
          { rank: '35', city: 'Milan', country: 'Italy' },
          { rank: '37', city: 'Vienna', country: 'Austria' },
          { rank: '41', city: 'Berlin', country: 'Germany' },
          { rank: '43', city: 'Athens', country: 'Greece' },
          { rank: '45', city: 'Moscow', country: 'Russia' },
          { rank: '46', city: 'Venice', country: 'Italy' },
          { rank: '47', city: 'Madrid', country: 'Spain' },
          { rank: '50', city: 'Dublin', country: 'Ireland' },
          { rank: '51', city: 'Florence', country: 'Italy' },
          { rank: '56', city: 'Munich', country: 'Germany' },
          { rank: '59', city: 'St. Petersburg', country: 'Russia' },
          { rank: '60', city: 'Brussels', country: 'Belgium' },
          { rank: '62', city: 'Budapest', country: 'Hungary' },
          { rank: '63', city: 'Lisbon', country: 'Portugal' },
          { rank: '66', city: 'Heraklion', country: 'Greece' },
          { rank: '71', city: 'Copenhagen', country: 'Denmark' },
          { rank: '87', city: 'Frankfurt', country: 'Germany' },
          { rank: '96', city: 'Porto', country: 'Portugal' },
          { rank: '74', city: 'Krakow', country: 'Poland' },
          { rank: '83', city: 'Warsaw', country: 'Poland' },
          { rank: '84', city: 'Mugla', country: 'Turkey' },
          { rank: '88', city: 'Stockholm', country: 'Sweden' },
          { rank: '92', city: 'Nice', country: 'France' },
          { rank: '97', city: 'Rhodes', country: 'Greece' },
        ],
      },
      {
        title: 'northAmerica',
        countries: '23',
        languages: '430',
        description:
          'A América do Norte está localizada no extremo norte das Américas e é composta por apenas três países: Estados Unidos, Canadá e México, além de territórios de domínios europeus, como a Groelândia (pertencente ao Reino da Dinamarca, com representação no parlamento) e Bermudas (dependência britânica).',
        image: '/continents/northAmerica.jpg',
        mostVisitedCities: [
          { rank: '8', city: 'New York City', country: 'US' },
          { rank: '27', city: 'Miami', country: 'US' },
          { rank: '29', city: 'Los Angeles', country: 'US' },
          { rank: '34', city: 'Las Vegas', country: 'US' },
          { rank: '40', city: 'Cancun', country: 'Mexico' },
          { rank: '44', city: 'Orlando', country: 'US' },
          { rank: '53', city: 'Toronto', country: 'Canada' },
          { rank: '69', city: 'Vancouver', country: 'Canada' },
          { rank: '72', city: 'San Francisco', country: 'US' },
          { rank: '81', city: 'Honolulu', country: 'US' },
        ],
      },
      {
        title: 'oceania',
        countries: '22',
        languages: '450',
        description:
          'A Oceania é um continente localizado a sudeste da Ásia, compreendendo um conjunto de ilhas somado à Austrália, essa última considerada como uma massa continental chamada de “Australásia”. Possui uma área total de 8.480.355 km², onde habitam aproximadamente 38 milhões de pessoas.',
        image: '/continents/oceania.jpg',
        mostVisitedCities: [
          { rank: '55', city: 'Sydney', country: 'Australia' },
          { rank: '73', city: 'Melbourne', country: 'Australia' },
          { rank: '78', city: 'Auckland', country: 'New Zealand' },
        ],
      },
      {
        title: 'southAmerica',
        countries: '14',
        languages: '448',
        description:
          'A América do Sul está localizada em grande parte no hemisfério sul, na zona intertropical ocidental. A América do Sul abrange um território de 18 milhões de quilômetros quadrados e é banhada a leste pelo oceano Atlântico, a oeste pelo oceano Pacífico e ao norte pelo mar das Antilhas, conhecido como do Caribe.',
        image: '/continents/southAmerica.jpg',
        mostVisitedCities: [
          { rank: '85', city: 'Buenos Aires City', country: 'Argentina' },
          { rank: '89', city: 'Lima', country: 'Peru' },
          { rank: '98', city: 'Rio de Janeiro', country: 'Brazil' },
        ],
      },
    ]);
  } else {
    return res.status(404).json({ message: 'not found' });
  }
}
